name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      github_token: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.COMMIT_SECRET }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --debug
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          git config --global user.email dannel_lim@hotmail.com
          git config --global user.name dannel_lim
          git status
          git remote add origin https://dannellim:${{github.token}}@github.com/${{github.repository}}.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
